version: '3.8'
services:
  concierge_staging:
    image: concierge:staging
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    environment:
      - ENV=staging
    restart: unless-stopped

  concierge_canary:
    image: concierge:canary
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8003:8000"
    environment:
      - ENV=canary
    restart: unless-stopped
