#!/usr/bin/env python3
"""Regression tests for image workflow prompt resolution and nested event loops."""
from __future__ import annotations

import asyncio
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))


def test_resolve_prompt_from_goal() -> None:
    from tools.image_prompt_utils import resolve_image_prompt

    subject = resolve_image_prompt(
        title="Generate image",
        instructions="Submit the prompt to the image generation plugin and return the result URL.",
        goal="generate a new logo for concierge",
    )
    assert subject == "generate a new logo for concierge", subject


def test_is_generation_not_prepare() -> None:
    from tools.image_prompt_utils import is_image_generation_task, is_prepare_image_prompt_task

    assert is_prepare_image_prompt_task(
        "Prepare image prompt",
        "Formulate a detailed, descriptive prompt for image generation: make a logo for concierge",
    )
    assert not is_image_generation_task("Prepare image prompt", "Formulate a detailed prompt")
    assert not is_image_generation_task(
        "Prepare image prompt",
        "Formulate a detailed, descriptive prompt for image generation: make a logo for concierge",
    )
    assert is_image_generation_task("Generate image", "Submit the prompt to the image generation plugin")


def test_prepare_step_not_routed_to_coding_agent() -> None:
    from tasks.step_assistant_tasks import _route_task_to_agent
    from task_agent import TaskAgent
    from agents.coding_agent import CodingAgent
    from tools.llm_tool import LLMTool
    from memory.memory_store import MemoryStore

    task = {
        "task_id": "t1",
        "title": "Prepare image prompt",
        "instructions": "Formulate a detailed, descriptive prompt for image generation: make a logo for concierge",
    }
    llm = LLMTool()
    memory = MemoryStore(llm_tool=llm)
    agent = _route_task_to_agent(task, memory, llm)
    assert isinstance(agent, TaskAgent), type(agent)
    assert not isinstance(agent, CodingAgent)


def test_coding_keyword_word_boundaries() -> None:
    from tasks.step_assistant_tasks import _contains_keyword

    assert not _contains_keyword("formulate a detailed, descriptive prompt", ["script"])
    assert _contains_keyword("write a python script for etl", ["script"])


def test_extract_goal_and_prepared_prompt() -> None:
    from tools.image_prompt_utils import extract_goal_from_instructions, extract_prepared_image_prompt

    instr = "Formulate a detailed, descriptive prompt for image generation: make a logo for concierge"
    assert extract_goal_from_instructions(instr) == "make a logo for concierge"
    prepared = extract_prepared_image_prompt(
        "Image prompt: Minimalist vector logo for Concierge, navy and gold, flat design"
    )
    assert prepared and "Concierge" in prepared


def test_rule_based_prepare_not_image_plugin() -> None:
    from tools.llm_tool import _rule_based_response

    coding_prompt = (
        "Write concise, working code to accomplish the following task.\n"
        "Return ONLY the code with no markdown fences or extra explanation.\n\n"
        "Task: Formulate a detailed, descriptive prompt for image generation: make a logo for concierge"
    )
    out = _rule_based_response(coding_prompt, context="make a logo for concierge")
    assert "Image generated by" not in out, out
    assert "Image prompt:" in out, out
    assert "logo" in out.lower(), out


def test_task_execution_prepare_not_image_plugin() -> None:
    from tools.llm_tool import _task_execution_reply

    prompt = (
        "Prepare image prompt: Formulate a detailed, descriptive prompt for image generation: "
        "make a logo for concierge\nProvide a concise result."
    )
    out = _task_execution_reply(prompt, context="Goal: make a logo for concierge")
    assert "Image generated by" not in out, out
    assert "Image prompt:" in out, out


async def _nested_plugin_call() -> str:
    from tools.llm_tool import _task_execution_reply

    prompt = (
        "Generate image: Submit the prompt to the image generation plugin and return the result URL.\n"
        "Provide a concise result."
    )
    # Must not raise RuntimeError: asyncio.run() cannot be called from a running event loop
    return _task_execution_reply(prompt, context="Goal: generate a new logo for concierge")


def test_nested_event_loop_safe() -> None:
    result = asyncio.run(_nested_plugin_call())
    assert "asyncio.run() cannot be called" not in result, result
    assert "generate a new logo for concierge" in result, result


def main() -> int:
    test_resolve_prompt_from_goal()
    test_is_generation_not_prepare()
    test_prepare_step_not_routed_to_coding_agent()
    test_coding_keyword_word_boundaries()
    test_extract_goal_and_prepared_prompt()
    test_rule_based_prepare_not_image_plugin()
    test_task_execution_prepare_not_image_plugin()
    test_nested_event_loop_safe()
    print("OK: image workflow fix tests passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())